---
# Check current preps
- import_tasks: preflight.yml
  tags:
    - always

# Set Parameters
- name: Define nginxlog_exporter_system_user
  set_fact:
    nginxlog_exporter_system_user: "{{ _nginxlog_exporter_system_user }}"
  when: nginxlog_exporter_system_user is not defined

- name: Define nginxlog_exporter_system_group
  set_fact:
    nginxlog_exporter_system_group: "{{ _nginxlog_exporter_system_group }}"
  when: nginxlog_exporter_system_group is not defined


# Install nginxlog_exporter
- import_tasks: install.yml
  become: true
  when:
    ( not _nginxlog_exporter_is_installed.stat.exists ) or 
    ( nginxlog_exporter_install_dir | length > 0 )

- import_tasks: configure.yml
  become: true
  tags:
    - postgres_exporter_configure