---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: puller23.nginxlog_exporter

  post_tasks:
    - name: Check if nginxlog_exporter is running.
      wait_for:
        host: 127.0.0.1
        port: 4040
        delay: 0
        timeout: 3